import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/app/(shared)/_Navbar/page";
import Footer from "@/app/(shared)/_Footer/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}

// const RootLayout = ({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) => (
//   <html lang="en">
//     <body className={inter.className}>
//       <Navbar />
//       {children}
//       <Footer />
//     </body>
//   </html>
// );

// export default RootLayout;
