import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/app/(shared)/_Navbar/page";
import Footer from "@/app/(shared)/_Footer/page";
// import { Provider } from "react-redux";
// import { store } from "../store/index";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // <Provider store={store}>
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
    // </Provider>
  );
}

// const RootLayout = ({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) => (
//   <html lang="en">
//     <body className={inter.className}>
//       <Navbar />
//       {children}
//       <Footer />
//     </body>
//   </html>
// );

// export default RootLayout;
